import Foundation
import AppKit
import Combine
import SwiftData
import UniformTypeIdentifiers

// MARK: - Clipboard Monitor Protocol

protocol ClipboardMonitorDelegate: AnyObject {
    func clipboardMonitor(_ monitor: ClipboardMonitor, didCaptureItem item: ClipboardItem)
    func clipboardMonitor(_ monitor: ClipboardMonitor, didEncounterError error: ClipboardMonitorError)
}

// MARK: - Clipboard Monitor Errors

enum ClipboardMonitorError: LocalizedError {
    case accessDenied
    case contentTooLarge(size: Int)
    case unsupportedType
    case processingFailed(underlying: Error)
    case ignoredByRule(reason: String)

    var errorDescription: String? {
        switch self {
        case .accessDenied:
            return "Clipboard access denied"
        case .contentTooLarge(let size):
            return "Content too large: \(ByteCountFormatter.string(fromByteCount: Int64(size), countStyle: .file))"
        case .unsupportedType:
            return "Unsupported clipboard content type"
        case .processingFailed(let error):
            return "Processing failed: \(error.localizedDescription)"
        case .ignoredByRule(let reason):
            return "Ignored: \(reason)"
        }
    }
}

// MARK: - Clipboard Monitor

/// Monitors the system clipboard for changes on macOS
final class ClipboardMonitor: ObservableObject {
    // MARK: - Properties

    weak var delegate: ClipboardMonitorDelegate?

    @Published private(set) var isMonitoring = false
    @Published private(set) var lastCapturedAt: Date?
    @Published private(set) var capturedCount = 0

    private let pasteboard = NSPasteboard.general
    private var timer: Timer?
    private var lastChangeCount: Int
    private var lastContentHash: String?
    private let settings: AppSettings
    private var cancellables = Set<AnyCancellable>()

    // Internal marker to identify our own pastes
    private static let internalMarker = "com.clipboard.manager.internal"
    private static let internalMarkerType = NSPasteboard.PasteboardType(internalMarker)

    // Concealed types from password managers
    private static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.1password.Concealed"
    ]

    // MARK: - Initialization

    init(settings: AppSettings) {
        self.settings = settings
        self.lastChangeCount = pasteboard.changeCount

        setupNotifications()
    }

    deinit {
        stop()
    }

    // MARK: - Setup

    private func setupNotifications() {
        NotificationCenter.default.publisher(for: .clipboardCheckIntervalChanged)
            .sink { [weak self] _ in
                guard let self = self, self.isMonitoring else { return }
                self.restart()
            }
            .store(in: &cancellables)

        // Handle app becoming active/inactive
        NotificationCenter.default.publisher(for: NSApplication.didBecomeActiveNotification)
            .sink { [weak self] _ in
                self?.checkForChanges()
            }
            .store(in: &cancellables)
    }

    // MARK: - Control Methods

    /// Start monitoring the clipboard
    func start() {
        guard !isMonitoring else { return }

        lastChangeCount = pasteboard.changeCount
        isMonitoring = true

        timer = Timer.scheduledTimer(
            withTimeInterval: settings.clipboardCheckInterval,
            repeats: true
        ) { [weak self] _ in
            self?.checkForChanges()
        }

        // Add to common run loop mode for reliability
        if let timer = timer {
            RunLoop.main.add(timer, forMode: .common)
        }
    }

    /// Stop monitoring the clipboard
    func stop() {
        timer?.invalidate()
        timer = nil
        isMonitoring = false
    }

    /// Restart monitoring (e.g., after settings change)
    func restart() {
        stop()
        start()
    }

    // MARK: - Change Detection

    private func checkForChanges() {
        let currentChangeCount = pasteboard.changeCount

        guard currentChangeCount != lastChangeCount else { return }
        lastChangeCount = currentChangeCount

        // Check if this is our own paste
        if pasteboard.types?.contains(Self.internalMarkerType) == true {
            return
        }

        processClipboardContent()
    }

    // MARK: - Content Processing

    private func processClipboardContent() {
        // Get the frontmost application
        let frontmostApp = NSWorkspace.shared.frontmostApplication
        let bundleID = frontmostApp?.bundleIdentifier
        let appName = frontmostApp?.localizedName

        // Check if app is ignored
        if let bundleID = bundleID, settings.shouldIgnoreApp(bundleID) {
            delegate?.clipboardMonitor(self, didEncounterError: .ignoredByRule(reason: "App '\(appName ?? bundleID)' is ignored"))
            return
        }

        // Check for password manager concealed content
        if settings.enablePasswordManagerDetection {
            if containsConcealedContent() {
                delegate?.clipboardMonitor(self, didEncounterError: .ignoredByRule(reason: "Password manager content detected"))
                return
            }
        }

        // Determine content type and extract data
        guard let (contentType, item) = extractClipboardContent(
            sourceAppBundleID: bundleID,
            sourceAppName: appName
        ) else {
            return
        }

        // Check for duplicates
        if shouldIgnoreDuplicate(item) {
            return
        }

        // Check for ignored patterns
        if let text = item.text, settings.shouldIgnoreContent(text) {
            delegate?.clipboardMonitor(self, didEncounterError: .ignoredByRule(reason: "Content matches ignored pattern"))
            return
        }

        // Check size limits
        if settings.ignoreLargeItems && item.contentSize > settings.largeItemThreshold {
            delegate?.clipboardMonitor(self, didEncounterError: .contentTooLarge(size: item.contentSize))
            return
        }

        // Mark as sensitive if needed
        if let text = item.text, settings.isSensitiveContent(text) {
            item.isSensitive = true
        }

        // Update stats
        lastCapturedAt = Date()
        capturedCount += 1
        lastContentHash = item.contentHash

        // Notify delegate
        delegate?.clipboardMonitor(self, didCaptureItem: item)

        // Play sound if enabled
        if settings.enableSound {
            NSSound.beep()
        }
    }

    // MARK: - Content Extraction

    private func extractClipboardContent(
        sourceAppBundleID: String?,
        sourceAppName: String?
    ) -> (ClipboardContentType, ClipboardItem)? {

        guard let types = pasteboard.types else { return nil }

        var availableTypes: [ClipboardContentType] = []
        var primaryType: ClipboardContentType = .unknown
        var text: String?
        var imageData: Data?
        var fileURL: URL?
        var rtfData: Data?
        var htmlContent: String?

        // Check all available types
        for type in types {
            if let contentType = mapPasteboardType(type) {
                availableTypes.append(contentType)
            }
        }

        // Extract text content
        if let string = pasteboard.string(forType: .string) {
            text = settings.trimWhitespace ? string.trimmingCharacters(in: .whitespacesAndNewlines) : string

            // Skip empty strings
            if text?.isEmpty == true {
                return nil
            }

            primaryType = .plainText
        }

        // Extract RTF if available
        if let rtf = pasteboard.data(forType: .rtf) {
            rtfData = rtf
            if primaryType == .unknown {
                primaryType = .rtf
            }
        }

        // Extract HTML if available
        if let html = pasteboard.string(forType: .html) {
            htmlContent = html
            if primaryType == .unknown {
                primaryType = .html
            }
        }

        // Extract image
        if types.contains(.png) || types.contains(.tiff) {
            if let data = pasteboard.data(forType: .png) {
                imageData = processImageData(data, type: .png)
                if primaryType == .unknown {
                    primaryType = .png
                }
            } else if let data = pasteboard.data(forType: .tiff) {
                imageData = processImageData(data, type: .tiff)
                if primaryType == .unknown {
                    primaryType = .tiff
                }
            }
        }

        // Extract file URL
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: nil) as? [URL],
           let url = urls.first {
            fileURL = url
            text = text ?? url.lastPathComponent
            if primaryType == .unknown {
                primaryType = url.isFileURL ? .fileURL : .url
            }
        }

        // Must have some content
        guard text != nil || imageData != nil || fileURL != nil else {
            return nil
        }

        let item = ClipboardItem(
            text: text,
            imageData: imageData,
            fileURL: fileURL,
            contentType: primaryType,
            availableTypes: availableTypes,
            sourceAppBundleID: sourceAppBundleID,
            sourceAppName: sourceAppName,
            isSensitive: false,
            rtfData: rtfData,
            htmlContent: htmlContent
        )

        return (primaryType, item)
    }

    // MARK: - Helper Methods

    private func containsConcealedContent() -> Bool {
        guard let types = pasteboard.types else { return false }

        for type in types {
            if Self.concealedTypes.contains(type.rawValue) {
                return true
            }
        }

        return false
    }

    private func shouldIgnoreDuplicate(_ item: ClipboardItem) -> Bool {
        switch settings.duplicateDetection {
        case .none:
            return false
        case .consecutive:
            return item.contentHash == lastContentHash
        case .all:
            // This would require checking against stored items
            // Handled at the storage layer
            return item.contentHash == lastContentHash
        }
    }

    private func mapPasteboardType(_ type: NSPasteboard.PasteboardType) -> ClipboardContentType? {
        switch type {
        case .string:
            return .plainText
        case .rtf:
            return .rtf
        case .html:
            return .html
        case .png:
            return .png
        case .tiff:
            return .tiff
        case .pdf:
            return .pdf
        case .fileURL:
            return .fileURL
        case .URL:
            return .url
        default:
            return nil
        }
    }

    private func processImageData(_ data: Data, type: ClipboardContentType) -> Data? {
        // Check size limit
        guard data.count <= settings.imageMaxSize else {
            delegate?.clipboardMonitor(self, didEncounterError: .contentTooLarge(size: data.count))
            return nil
        }

        // Optionally compress large images
        if data.count > 1_000_000 { // > 1MB
            return compressImageData(data)
        }

        return data
    }

    private func compressImageData(_ data: Data) -> Data? {
        guard let image = NSImage(data: data) else { return data }

        // Convert to JPEG with compression
        guard let tiffData = image.tiffRepresentation,
              let bitmap = NSBitmapImageRep(data: tiffData) else {
            return data
        }

        return bitmap.representation(
            using: .jpeg,
            properties: [.compressionFactor: 0.8]
        )
    }

    // MARK: - Paste Operations

    /// Write content to clipboard (with internal marker)
    func writeToClipboard(_ item: ClipboardItem, removeFormatting: Bool = false) {
        pasteboard.clearContents()

        var items: [NSPasteboardItem] = []
        let pasteboardItem = NSPasteboardItem()

        // Add internal marker
        pasteboardItem.setData(Data(), forType: Self.internalMarkerType)

        // Add text content
        if let text = item.text {
            pasteboardItem.setString(text, forType: .string)

            // Add rich content unless removing formatting
            if !removeFormatting {
                if let rtfData = item.rtfData {
                    pasteboardItem.setData(rtfData, forType: .rtf)
                }
                if let htmlContent = item.htmlContent {
                    pasteboardItem.setString(htmlContent, forType: .html)
                }
            }
        }

        // Add image content
        if let imageData = item.imageData {
            pasteboardItem.setData(imageData, forType: .png)
        }

        // Add file URL
        if let fileURL = item.fileURL {
            pasteboardItem.setString(fileURL.absoluteString, forType: .fileURL)
        }

        items.append(pasteboardItem)
        pasteboard.writeObjects(items)

        // Update change count to prevent re-capture
        lastChangeCount = pasteboard.changeCount
    }

    /// Simulate paste action (Cmd+V)
    func simulatePaste() {
        let source = CGEventSource(stateID: .combinedSessionState)

        // Key down
        let keyDown = CGEvent(keyboardEventSource: source, virtualKey: 0x09, keyDown: true)
        keyDown?.flags = .maskCommand
        keyDown?.post(tap: .cghidEventTap)

        // Key up
        let keyUp = CGEvent(keyboardEventSource: source, virtualKey: 0x09, keyDown: false)
        keyUp?.flags = .maskCommand
        keyUp?.post(tap: .cghidEventTap)
    }
}

// MARK: - Pasteboard Extensions

extension NSPasteboard.PasteboardType {
    static let png = NSPasteboard.PasteboardType("public.png")
}
